apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: php-app
spec:
  selector:
    app: php-app
  type: NodePort
  ports:
   - name: http
     port: 80
     targetPort: 80
     nodePort: 30001
     protocol: TCP