version: "3.7"

services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
    networks:
      - booksnet

  myapp:
    build: .
    container_name: bookstore
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - booksnet

networks:
  booksnet:
    driver: bridge
