version: "3.7"

services:
    database:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: R1234r
            MYSQL_DATABASE: mydatabase
            MYSQL_USER: mehmet
            MYSQL_PASSWORD: 123456789
        networks:
            - phpnet
    myapp:
        image: blgsyrc0560/web-server-php:5.0
        restart: always
        environment:
            DATABASE_HOST: database
            DATABASE_NAME: mydatabase
            DATABASE_USERNAME: mehmet
            DATABASE_PASSWORD: 123456789
        depends_on:
            - database
        ports:
            - "80:80"
        networks:
            - phpnet

networks:
    phpnet:
        driver: bridge
